// AUTO-GENERATED by `cargo xtask gen-manifest` - DO NOT EDIT

import type { Highlight } from "./types.js"; 

/** Version of plugin packages (all @arborium/* packages share this version) */
export const pluginVersion = "<%= version %>";

/** All available languages */
export const availableLanguages: string[] = [
<% for lang in languages { %>  "<%= lang %>",
<% } %>];

/** All possible highlights and their short tags */
export const highlights: Highlight[] = [
<% for hl in highlights { %>  {
    name: "<%= hl.name %>",
    tag: "<%= hl.def.tag %>",<% if let Some(parent) = &hl.def.parent { %>
    parentTag: "<%= parent %>",<% } %>
  },
<% } %>];

/** The exact capture-to-tag mapping used by the Rust HTML renderer. */
const captureTags = new Map<string, string | null>([
<% for name in crate::highlight_gen::render_highlights::CAPTURE_NAMES { %>
  ["<%= name %>", <%- crate::highlight_gen::render_highlights::tag_for_capture(name).map(|tag| format!("\"{tag}\"")).unwrap_or_else(|| "null".into()) %>],
<% } %>
]);
const capturePrefixes: [string, string][] = [
<% for (prefix, slot) in crate::highlight_gen::render_highlights::CAPTURE_PREFIXES { %>
  ["<%= prefix %>", "<%= slot.tag().unwrap_or("") %>"],
<% } %>
];

/**
 * Get the short tag suffix used by HTML and theme CSS, e.g. `function.call` → `f`.
 * Returns null for captures with no styling. A leading @ is accepted.
 */
export function getTagForCapture(capture: string): string | null {
  const name = capture.startsWith("@") ? capture.slice(1) : capture;
  if (captureTags.has(name)) return captureTags.get(name)!;
  return capturePrefixes.find(([prefix]) => name.startsWith(prefix))?.[1] ?? null;
}
